### ISSUE TITLE
Error while conducting experiment

### ISSUE THREAD

**Issue by mustansarsaeed** [PlatformLab/homa-paper-artifact#1]
Hi, I have resvered full chassis on Ramcloud but getting error to generate numbers. When 
I run the command,
`$ scripts/clusterperf.py --superuser --replicas 0 --transport homa+dpdk --dpdkPort 1 --verbose echo_basic
` 

I get the following error:

```
Traceback (most recent call last):
  File "scripts/clusterperf.py", line 1101, in <module>
    run_test(test, options)
  File "scripts/clusterperf.py", line 384, in run_test
    test.function(test.name, options, cluster_args, client_args)
  File "scripts/clusterperf.py", line 434, in echo
    default(name, options, cluster_args, client_args)
  File "scripts/clusterperf.py", line 411, in default
    flatten_args(client_args), name), **cluster_args)
  File "/shome/RAMCloud/scripts/cluster.py", line 603, in run
    % (num_servers, len(getHosts())))
  File "/shome/RAMCloud/scripts/common.py", line 328, in getHosts
    "\tplease specify a custom hosts list in scripts/localconfig.py" % rcresOutput)
Exception: config.py could not invoke rcres (sh: 1: rcres: not found);
	please specify a custom hosts list in scripts/localconfig.py

```

Can you please help me in this regard.

**Comment by mustansarsaeed** [comment]
it has been executed successfully, there was a mistake at my end.
